# Generated by Django 2.2.1 on 2019-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190604_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('J', 'Jumbo 5X Burgers'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
