# Generated by Django 2.2.1 on 2019-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190612_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('J', 'rolls Express'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
